namespace chord {
	using namespace std;
	typedef array<uint8_t, 12> key_t;
	struct chord_t {
		enum fmt_type {
			BASS,
			BASS_BASS,
			BASS_ROOT_BASS,
			ROOT,
			ROOT_BASS,
			NONE
		};
		const fmt_type fmt = NONE;
		const char* fmt_str = nullptr;
		const uint8_t nth_root = 0;
		int format_to_string(char* str, const char* bass_key, const char* nth_key) const {			
			switch (fmt) {
				case BASS: return sprintf(str, fmt_str, bass_key);
				case BASS_BASS: return sprintf(str, fmt_str, bass_key, bass_key);
				case BASS_ROOT_BASS: return sprintf(str, fmt_str, bass_key, nth_key, bass_key);
				case ROOT: return sprintf(str, fmt_str, nth_key);
				case ROOT_BASS: return sprintf(str, fmt_str, nth_key, bass_key);
				case NONE:
				default:
					return sprintf(str, "%s", fmt_str);
			}
		}
	};
	class chord_arr_t {
		using container_type = array<chord_t, 8>;
		const container_type chords;
		const size_t num_chords;
	public:
		template<typename... T> constexpr explicit chord_arr_t(T... args) : chords{ args... }, num_chords(sizeof...(args)) {}
		container_type::const_iterator begin() const { return chords.begin(); }
		container_type::const_iterator end() const { return chords.begin() + num_chords; }
		size_t size() const { return num_chords; }
	};
	/****/
	typedef pair<key_t, chord_arr_t> chord_item_t;
	const char* key_table[] = { "C" ,"Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B" };
	const char* interval_table[] = { "Oct","min 2nd","Maj 2nd","min 3rd","Maj 3rd","Perfect 4th","Tritone","Perfect 5th","min 6th","Maj 6th","min 7th","Maj 7th" };
	const chord_item_t chord_table[] = {
			{{1, 3, 4}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 0},}},
			{{1, 3, 4, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11(no5)/ %s", 0},}},
			{{1, 3, 4, 6, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 1},}},
			{{1, 3, 4, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 1},}},
			{{1, 3, 4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(#9b9#11)", 0},chord_t{ chord_t::BASS,"%sDiminished Half - Whole", 0},}},
			{{1, 3, 4, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 3},}},
			{{1, 3, 4, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11/ %s", 0},}},
			{{1, 3, 4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7alt", 0},chord_t{ chord_t::BASS,"%sAltered", 0},chord_t{ chord_t::NONE,"Super Locrian", 0},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13/ %s", 0},}},
			{{1, 3, 4, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(#9b9#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 3},}},
			{{1, 3, 4, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#9b9b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13(no5)/ %s", 0},}},
			{{1, 3, 4, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 1},}},
			{{1, 3, 4, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#11)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 1},}},
			{{1, 3, 4, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(#9b9)", 0},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 1},}},
			{{1, 3, 4, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9#9)", 0},chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 1},}},
			{{1, 3, 4, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 0},}},
			{{1, 3, 4, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#9b9#5)", 0},chord_t{ chord_t::ROOT_BASS,"%sm11(b5)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%smM9(13)/ %s", 0},}},
			{{1, 3, 4, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(#9b9)", 0},}},
			{{1, 3, 4, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9#9)", 0},chord_t{ chord_t::ROOT_BASS,"%smM9(13)no5/ %s", 0},}},
			{{1, 3, 5}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 0},}},
			{{1, 3, 5, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 1},}},
			{{1, 3, 5, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 0},}},
			{{1, 3, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sLocrian", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 3},}},
			{{1, 3, 5, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9b13)/ %s", 2},}},
			{{1, 3, 5, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9b13)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 3},}},
			{{1, 3, 5, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 0},}},
			{{1, 3, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 0},}},
			{{1, 3, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sPhrygian", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 0},}},
			{{1, 3, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(#9#5b5)/ %s", 4},}},
			{{1, 3, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sDorian(b2)", 0},chord_t{ chord_t::ROOT_BASS,"%s7alt/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%smM13/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 1},}},
			{{1, 3, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 2},}},
			{{1, 3, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 1},}},
			{{1, 3, 5, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9b13/ %s", 2},}},
			{{1, 3, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 1},}},
			{{1, 3, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#5)/ %s", 0},}},
			{{1, 3, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11/ %s", 4},}},
			{{1, 3, 5, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm(add9,11)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 2},}},
			{{1, 3, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 1},}},
			{{1, 3, 6, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 1},}},
			{{1, 3, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 1},}},
			{{1, 3, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 4},}},
			{{1, 3, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 1},}},
			{{1, 3, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 3},}},
			{{1, 3, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 3},}},
			{{1, 3, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 1},}},
			{{1, 3, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 1},}},
			{{1, 3, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(11)/ %s", 3},}},
			{{1, 3, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 4},}},
			{{1, 3, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9b5)/ %s", 3},}},
			{{1, 3, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9b5)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13(no5)/ %s", 4},}},
			{{1, 3, 7, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 1},}},
			{{1, 3, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd11/ %s", 2},}},
			{{1, 3, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 1},}},
			{{1, 3, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11(no5)/ %s", 3},}},
			{{1, 4}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj7/ %s", 0},}},
			{{1, 4, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9b13/ %s", 4},}},
			{{1, 4, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 0},}},
			{{1, 4, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 4},}},
			{{1, 4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(b9#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 4},}},
			{{1, 4, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9#11)", 0},}},
			{{1, 4, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 0},}},
			{{1, 4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9#5b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s9#11/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 0},}},
			{{1, 4, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(b9#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9#11)/ %s", 2},}},
			{{1, 4, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#11)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 0},}},
			{{1, 4, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%s(b9)", 0},}},
			{{1, 4, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9b13)", 0},}},
			{{1, 4, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 3},}},
			{{1, 4, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13b9", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 3},}},
			{{1, 4, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7b9", 0},}},
			{{1, 4, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj7/ %s", 0},}},
			{{1, 4, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(b9#5)", 0},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm9b5/ %s", 3},}},
			{{1, 4, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(#9)/ %s", 2},}},
			{{1, 4, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13b9", 0},}},
			{{1, 4, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7b9", 0},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 0},}},
			{{1, 5}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7/ %s", 0},}},
			{{1, 5, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(11)/ %s", 0},}},
			{{1, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 2},}},
			{{1, 5, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(#11)/ %s", 2},}},
			{{1, 5, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7b5/ %s", 0},}},
			{{1, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(#11)/ %s", 0},}},
			{{1, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4(b9b13)", 0},chord_t{ chord_t::BASS,"%s7(b9b13sus)", 0},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 0},}},
			{{1, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#5)/ %s", 3},}},
			{{1, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13sus4(b9)", 0},chord_t{ chord_t::ROOT_BASS,"%sm11(b5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9#5)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM9(13)/ %s", 4},}},
			{{1, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4(b9)", 0},chord_t{ chord_t::BASS,"%s7b9sus", 0},chord_t{ chord_t::ROOT_BASS,"%sm6/9/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm11b5/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm7b5add11/ %s", 2},}},
			{{1, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm(b6)/ %s", 1},}},
			{{1, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(13)/ %s", 0},chord_t{ chord_t::BASS,"%s7sus4(b9b13)", 0},chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 3},}},
			{{1, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(#5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s(b6)/ %s", 1},}},
			{{1, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13sus4(b9)", 0},chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 3},}},
			{{1, 5, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4(b9)", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm(add9)/ %s", 2},}},
			{{1, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s5(#11)/ %s", 1},}},
			{{1, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 3},}},
			{{1, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 3},}},
			{{1, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 2},}},
			{{1, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 2},}},
			{{1, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm(#11)/ %s", 1},}},
			{{1, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(#11)/ %s", 1},}},
			{{1, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 3},}},
			{{1, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 2},}},
			{{1, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM9(13)no5/ %s", 3},}},
			{{1, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd11/ %s", 1},}},
			{{1, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 2},}},
			{{1, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 2},}},
			{{1, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm(add9)/ %s", 1},}},
			{{2, 3}, chord_arr_t{chord_t{ chord_t::BASS,"%sm(add9)", 0},}},
			{{2, 3, 5, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7mM9(13)no5/ %s", 1},}},
			{{2, 3, 5, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9b9b5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%smM13(no5)/ %s", 1},}},
			{{2, 3, 5, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 4},}},
			{{2, 3, 5, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 0},chord_t{ chord_t::BASS,"%sDiminished Whole - Half", 0},}},
			{{2, 3, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sLocrian Natural(9)", 0},chord_t{ chord_t::ROOT_BASS,"%s7alt/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%smM13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 4},}},
			{{2, 3, 5, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 0},}},
			{{2, 3, 5, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 0},}},
			{{2, 3, 5, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 2},}},
			{{2, 3, 5, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm11(b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9#5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%smM9(13)/ %s", 1},}},
			{{2, 3, 5, 6, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 0},}},
			{{2, 3, 5, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sm(add9,11)", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 3},}},
			{{2, 3, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9b13)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 4},}},
			{{2, 3, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sAeolian", 0},chord_t{ chord_t::NONE,"Natural Minor", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 4},}},
			{{2, 3, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 3},}},
			{{2, 3, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm13", 0},chord_t{ chord_t::BASS,"%sDorian", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 1},}},
			{{2, 3, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM13", 0},chord_t{ chord_t::BASS,"%sMelodic Minor", 0},chord_t{ chord_t::ROOT_BASS,"%s7alt/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 2},}},
			{{2, 3, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm11", 0},chord_t{ chord_t::BASS_BASS,"%smin11; %s-11", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 2},}},
			{{2, 3, 5, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM11", 0},}},
			{{2, 3, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 2},}},
			{{2, 3, 5, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 2},}},
			{{2, 3, 5, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 5},}},
			{{2, 3, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 4},}},
			{{2, 3, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 2},}},
			{{2, 3, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm13", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 4},}},
			{{2, 3, 5, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM13(no5)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9b5)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 2},}},
			{{2, 3, 5, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm11", 0},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 2},}},
			{{2, 3, 5, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM11(no5)", 0},}},
			{{2, 3, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 1},}},
			{{2, 3, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#11)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(b9b5)/ %s", 0},}},
			{{2, 3, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#11)/ %s", 0},}},
			{{2, 3, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 5},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 0},}},
			{{2, 3, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#5b5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s9#11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 1},}},
			{{2, 3, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#11)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 0},}},
			{{2, 3, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 0},}},
			{{2, 3, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9b13)/ %s", 0},}},
			{{2, 3, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 4},}},
			{{2, 3, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm9b5", 0},chord_t{ chord_t::BASS_BASS,"%sø9;%s-9b5", 0},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(b9#5)/ %s", 0},}},
			{{2, 3, 6, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 0},}},
			{{2, 3, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sm(add9)", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 1},}},
			{{2, 3, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(#11)/ %s", 3},}},
			{{2, 3, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 3},}},
			{{2, 3, 7, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%sm6/9", 0},chord_t{ chord_t::BASS_BASS,"%smin6/9; %s-6/9", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm11b5/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm7b5add11/ %s", 3},}},
			{{2, 3, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm9(13)", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9b13)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 1},}},
			{{2, 3, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM9(13)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9#5)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%sm11(b5)/ %s", 3},}},
			{{2, 3, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm9", 0},chord_t{ chord_t::BASS_BASS,"%smin9; %s-9", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj7(13)/ %s", 1},}},
			{{2, 3, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smMaj9", 0},chord_t{ chord_t::BASS_BASS,"%sminMaj9; %s-Δ9", 0},}},
			{{2, 3, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(#11)/ %s", 2},}},
			{{2, 3, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 4},}},
			{{2, 3, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 3},}},
			{{2, 3, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm9(13)", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 3},}},
			{{2, 3, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM9(13)no5", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 3},}},
			{{2, 3, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm9", 0},}},
			{{2, 3, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smMaj9", 0},}},
			{{2, 4}, chord_arr_t{chord_t{ chord_t::BASS,"%sadd9", 0},}},
			{{2, 4, 5}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 0},}},
			{{2, 4, 5, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 3},}},
			{{2, 4, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11(b5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9#5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM9(13)/ %s", 2},}},
			{{2, 4, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sMixolydian(b13)", 0},chord_t{ chord_t::NONE,"Melodic Major(down)", 0},chord_t{ chord_t::ROOT_BASS,"%s7alt/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 5},}},
			{{2, 4, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 3},}},
			{{2, 4, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13", 0},chord_t{ chord_t::BASS,"%sMixolydian", 0},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 5},}},
			{{2, 4, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13", 0},chord_t{ chord_t::BASS,"%sIonian", 0},chord_t{ chord_t::NONE,"Natural Major", 0},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 2},}},
			{{2, 4, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s11", 0},}},
			{{2, 4, 5, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj11", 0},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 0},}},
			{{2, 4, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm9b5/ %s", 0},}},
			{{2, 4, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9#11/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s7(b9#5b5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 2},}},
			{{2, 4, 5, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9b13)/ %s", 1},}},
			{{2, 4, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj7(13)/ %s", 2},}},
			{{2, 4, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 4},}},
			{{2, 4, 5, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13", 0},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9b13)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 2},}},
			{{2, 4, 5, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s11", 0},}},
			{{2, 4, 5, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj11", 0},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 0},}},
			{{2, 4, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 0},}},
			{{2, 4, 6, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sadd9(#11)", 0},}},
			{{2, 4, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 0},}},
			{{2, 4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13#11", 0},chord_t{ chord_t::BASS,"%sLydian Dominant", 0},chord_t{ chord_t::ROOT_BASS,"%s7alt/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM13/ %s", 3},}},
			{{2, 4, 6, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13(#11)", 0},chord_t{ chord_t::BASS,"%sLydian", 0},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 0},}},
			{{2, 4, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s9#11", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#5b5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 3},}},
			{{2, 4, 6, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj9(#11)", 0},chord_t{ chord_t::BASS,"%sΔ9(#11)", 0},}},
			{{2, 4, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9(b5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s9(#5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(#5b5)/ %s", 3},}},
			{{2, 4, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9#11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#5b5)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 4},}},
			{{2, 4, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sLydian Augmented", 0},chord_t{ chord_t::ROOT_BASS,"%s7alt/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%smM13/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 0},}},
			{{2, 4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sWhole Tone", 0},}},
			{{2, 4, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9#5b5)/ %s", 3},}},
			{{2, 4, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 0},}},
			{{2, 4, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13#11", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9#5b5)/ %s", 2},}},
			{{2, 4, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13(#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 1},}},
			{{2, 4, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s9(b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s9(#5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#5b5)/ %s", 2},}},
			{{2, 4, 6, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj9(#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 0},}},
			{{2, 4, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sadd9", 0},chord_t{ chord_t::BASS,"%sadd2", 0},}},
			{{2, 4, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#5)/ %s", 1},}},
			{{2, 4, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s7(#9#5b5)/ %s", 1},}},
			{{2, 4, 7, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9b13/ %s", 1},}},
			{{2, 4, 7, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%s6/9", 0},chord_t{ chord_t::BASS,"%sPentatonic Major", 0},chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 3},}},
			{{2, 4, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 0},}},
			{{2, 4, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13", 0},chord_t{ chord_t::BASS,"%sΔ13", 0},chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 0},}},
			{{2, 4, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s9", 0},}},
			{{2, 4, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj9", 0},chord_t{ chord_t::BASS,"%sΔ9", 0},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 0},}},
			{{2, 4, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#5/ %s", 1},}},
			{{2, 4, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 3},}},
			{{2, 4, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11/ %s", 3},}},
			{{2, 4, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s9(#5)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#5b5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s9(b5)/ %s", 3},}},
			{{2, 4, 8, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj9(#5)", 0},chord_t{ chord_t::ROOT_BASS,"%s7b13/ %s", 1},}},
			{{2, 4, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7sus2/ %s", 0},}},
			{{2, 4, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 3},}},
			{{2, 4, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13", 0},chord_t{ chord_t::ROOT_BASS,"%sm(add9,11)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 1},}},
			{{2, 4, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s9", 0},}},
			{{2, 4, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj9", 0},}},
			{{2, 5}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7/ %s", 0},}},
			{{2, 5, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 0},}},
			{{2, 5, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9b5)/ %s", 0},}},
			{{2, 5, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 3},}},
			{{2, 5, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 3},}},
			{{2, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s7(#9#5b5)/ %s", 0},}},
			{{2, 5, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9#11)/ %s", 0},}},
			{{2, 5, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 0},}},
			{{2, 5, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9b13/ %s", 0},}},
			{{2, 5, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 0},}},
			{{2, 5, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#5)/ %s", 0},}},
			{{2, 5, 6, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 0},}},
			{{2, 5, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%ssus2/4", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 0},}},
			{{2, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11b5/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm6/9/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm7b5add11/ %s", 0},}},
			{{2, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4(b13)", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 4},}},
			{{2, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s6/9/ %s", 1},}},
			{{2, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13sus4", 0},chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 4},}},
			{{2, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 2},}},
			{{2, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s9sus4", 0},chord_t{ chord_t::BASS_ROOT_BASS,"%s11(no3); %s/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s6/9/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 2},}},
			{{2, 5, 7, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 0},}},
			{{2, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7b5/ %s", 0},}},
			{{2, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 3},}},
			{{2, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s6/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm7/ %s", 0},}},
			{{2, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13sus4", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 3},}},
			{{2, 5, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 0},}},
			{{2, 5, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s/ %s", 2},chord_t{ chord_t::BASS,"%s9sus4(no5)", 0},chord_t{ chord_t::ROOT_BASS,"%sm7#5/ %s", 0},}},
			{{2, 5, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sdim/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 0},}},
			{{2, 6}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 0},}},
			{{2, 6, 7}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 0},}},
			{{2, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 3},}},
			{{2, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11/ %s", 2},}},
			{{2, 6, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 3},}},
			{{2, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 2},}},
			{{2, 6, 7, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(11)/ %s", 2},}},
			{{2, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b5/ %s", 0},}},
			{{2, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s7(b9b5)/ %s", 2},}},
			{{2, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9b5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM13(no5)/ %s", 3},}},
			{{2, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9(b5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s9(#5)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s7(#5b5)/ %s", 0},}},
			{{2, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9b5)/ %s", 2},}},
			{{2, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 0},}},
			{{2, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b13/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#5)/ %s", 3},}},
			{{2, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 0},}},
			{{2, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#5/ %s", 0},}},
			{{2, 6, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 0},}},
			{{2, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%ssus2", 0},chord_t{ chord_t::BASS,"%s2", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(no5)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%ssus4/ %s", 1},}},
			{{2, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7b5/ %s", 2},}},
			{{2, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 2},}},
			{{2, 7, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%ssus2/6", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 2},}},
			{{2, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sm(add9,11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 3},}},
			{{2, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 0},}},
			{{2, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus2", 0},}},
			{{2, 7, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s/ %s", 1},chord_t{ chord_t::BASS,"%s Maj9(no3)", 0},}},
			{{2, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(b5)/ %s", 1},}},
			{{2, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 2},}},
			{{2, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11(no5)/ %s", 2},}},
			{{2, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 2},}},
			{{2, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(omit 3)/ %s", 0},}},
			{{2, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 2},}},
			{{2, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd9/ %s", 1},}},
			{{3, 4, 5, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sBlues(add3)", 0},}},
			{{3, 4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(#9#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s13(#9b9#11)/ %s", 2},}},
			{{3, 4, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#9#11)", 0},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 2},}},
			{{3, 4, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#5)/ %s", 1},}},
			{{3, 4, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9b13)/ %s", 3},}},
			{{3, 4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#9#5b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s13#11/ %s", 2},}},
			{{3, 4, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9b13/ %s", 3},}},
			{{3, 4, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13(#9#11)", 0},}},
			{{3, 4, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#9b5)", 0},}},
			{{3, 4, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%s(#9)", 0},}},
			{{3, 4, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7#9b13", 0},}},
			{{3, 4, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13#9", 0},}},
			{{3, 4, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7#9", 0},}},
			{{3, 4, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(#5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s(b6)/ %s", 2},}},
			{{3, 4, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#9#5)", 0},}},
			{{3, 4, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm(#11)/ %s", 2},}},
			{{3, 4, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13#9", 0},}},
			{{3, 4, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7#9", 0},}},
			{{3, 5}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(omit 3)/ %s", 1},}},
			{{3, 5, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sBlues", 0},}},
			{{3, 5, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 3},}},
			{{3, 5, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 1},}},
			{{3, 5, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 5},}},
			{{3, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b13)/ %s", 4},}},
			{{3, 5, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 3},}},
			{{3, 5, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 1},}},
			{{3, 5, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#11)/ %s", 1},}},
			{{3, 5, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7b5add11", 0},chord_t{ chord_t::BASS,"%sm11b5", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm6/9/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13(#11)/ %s", 2},}},
			{{3, 5, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sm(add11)", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus2/ %s", 1},}},
			{{3, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj7(13)/ %s", 3},}},
			{{3, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 4},}},
			{{3, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 1},}},
			{{3, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 1},}},
			{{3, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM13(no9)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#5b5)/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s9#11/ %s", 1},}},
			{{3, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7(11)", 0},chord_t{ chord_t::BASS,"%sPentatonic Minor", 0},chord_t{ chord_t::ROOT_BASS,"%s6/9/ %s", 0},}},
			{{3, 5, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM7(11)", 0},}},
			{{3, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s6/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm7/ %s", 1},}},
			{{3, 5, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 1},}},
			{{3, 5, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s13(b9#11)/ %s", 4},}},
			{{3, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s6/9/ %s", 2},}},
			{{3, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 1},}},
			{{3, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm13", 0},chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 1},}},
			{{3, 5, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM13(no9)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#11)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(b9b5)/ %s", 3},}},
			{{3, 5, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7(11)", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4/ %s", 1},}},
			{{3, 5, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM7(11)", 0},}},
			{{3, 6}, chord_arr_t{chord_t{ chord_t::BASS,"%sdim", 0},chord_t{ chord_t::BASS,"%sο", 0},}},
			{{3, 6, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sm(#11)", 0},}},
			{{3, 6, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9b13)/ %s", 4},}},
			{{3, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 2},}},
			{{3, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 2},}},
			{{3, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 4},chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 2},}},
			{{3, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 2},}},
			{{3, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 2},}},
			{{3, 6, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%sdim7", 0},chord_t{ chord_t::BASS,"%sο7", 0},}},
			{{3, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 3},}},
			{{3, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7b5", 0},chord_t{ chord_t::BASS_BASS,"%sø; %s-7b5", 0},}},
			{{3, 6, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(b9)/ %s", 2},}},
			{{3, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sm", 0},chord_t{ chord_t::BASS_BASS,"%smin; %s-", 0},chord_t{ chord_t::ROOT_BASS,"%s6/ %s", 0},}},
			{{3, 7, 8}, chord_arr_t{chord_t{ chord_t::BASS,"%sm(b6)", 0},chord_t{ chord_t::BASS_BASS,"%smin(b6); %s-(b6)", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj7/ %s", 2},}},
			{{3, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 3},}},
			{{3, 7, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%sm6", 0},chord_t{ chord_t::BASS_BASS,"%s-6; %smin6", 0},chord_t{ chord_t::ROOT_BASS,"%sm7b5/ %s", 2},}},
			{{3, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7(13)", 0},}},
			{{3, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM7(13)", 0},chord_t{ chord_t::ROOT_BASS,"%s7(b9#5)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm9b5/ %s", 2},}},
			{{3, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7", 0},chord_t{ chord_t::BASS_BASS,"%smin7; %s-7", 0},chord_t{ chord_t::ROOT_BASS,"%s6/ %s", 0},}},
			{{3, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smMaj7", 0},chord_t{ chord_t::BASS_BASS,"%sminMaj7; %s-Δ7", 0},}},
			{{3, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s/ %s", 1},chord_t{ chord_t::BASS,"%smin#5", 0},chord_t{ chord_t::BASS_BASS,"%sm#5; %s-#5;", 0},}},
			{{3, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(b9)/ %s", 1},}},
			{{3, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 3},}},
			{{3, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd9/ %s", 1},chord_t{ chord_t::BASS,"%sm7#5", 0},}},
			{{3, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(#9)/ %s", 1},}},
			{{3, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%sm6(no5)", 0},chord_t{ chord_t::ROOT_BASS,"%sdim/ %s", 1},}},
			{{3, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7(13)", 0},}},
			{{3, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smM7(13)", 0},chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 2},}},
			{{3, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sm7", 0},chord_t{ chord_t::BASS_BASS,"%smin7; %s-7", 0},}},
			{{3, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%smMaj7", 0},}},
			{{4, 5}, chord_arr_t{chord_t{ chord_t::BASS,"%sadd11", 0},}},
			{{4, 5, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%sadd11", 0},}},
			{{4, 5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 1},}},
			{{4, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11/ %s", 1},}},
			{{4, 5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s13sus4/ %s", 2},}},
			{{4, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 1},}},
			{{4, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 1},}},
			{{4, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s11", 0},chord_t{ chord_t::ROOT_BASS,"%sm13/ %s", 2},}},
			{{4, 5, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7(11)", 0},}},
			{{4, 5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj7/ %s", 1},}},
			{{4, 5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 1},}},
			{{4, 5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm(b6)/ %s", 2},}},
			{{4, 5, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(11)/ %s", 1},}},
			{{4, 5, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7(#11)/ %s", 1},}},
			{{4, 5, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s11", 0},}},
			{{4, 6}, chord_arr_t{chord_t{ chord_t::BASS,"%s(b5)", 0},chord_t{ chord_t::BASS,"%sMaj(b5)", 0},}},
			{{4, 6, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%s(#11)", 0},}},
			{{4, 6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 3},}},
			{{4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13#11", 0},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9b5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM13(no5)/ %s", 2},}},
			{{4, 6, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13(#11)", 0},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9b13)/ %s", 4},}},
			{{4, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#11)", 0},chord_t{ chord_t::ROOT_BASS,"%smM13(no9)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7(b9b5)/ %s", 1},}},
			{{4, 6, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7(#11)", 0},chord_t{ chord_t::BASS,"%sΔ7(#11)", 0},}},
			{{4, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#5/ %s", 2},}},
			{{4, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm9b5/ %s", 1},}},
			{{4, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm11(b5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7(#9b9#5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%smM9(13)/ %s", 3},}},
			{{4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(#5b5)", 0},chord_t{ chord_t::ROOT_BASS,"%s9(#5)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s9(b5)/ %s", 1},}},
			{{4, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9#5)/ %s", 2},}},
			{{4, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7b5/ %s", 1},}},
			{{4, 6, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(#9b5)/ %s", 1},}},
			{{4, 6, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13(#11)", 0},chord_t{ chord_t::ROOT_BASS,"%sm11b5/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 3},chord_t{ chord_t::ROOT_BASS,"%sm6/9/%s", 2},chord_t{ chord_t::ROOT_BASS,"%sm7b5add11/ %s", 1},}},
			{{4, 6, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7b5", 0},}},
			{{4, 6, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7b5", 0},}},
			{{4, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%s", 0},chord_t{ chord_t::BASS,"%sMaj", 0},chord_t{ chord_t::BASS,"3%s", 0},chord_t{ chord_t::BASS,"4%s", 0},chord_t{ chord_t::BASS,"5%s", 0},chord_t{ chord_t::BASS,"6%s", 0},}},
			{{4, 7, 8}, chord_arr_t{chord_t{ chord_t::BASS,"%s(b6)", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj7(#5)/ %s", 2},}},
			{{4, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7b13", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#5)/ %s", 2},}},
			{{4, 7, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%s6", 0},chord_t{ chord_t::ROOT_BASS,"%sm7/ %s", 2},}},
			{{4, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7add13", 0},}},
			{{4, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7(13)", 0},chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 2},}},
			{{4, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7", 0},}},
			{{4, 7, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7", 0},chord_t{ chord_t::BASS,"%sΔ7", 0},chord_t{ chord_t::ROOT_BASS,"%sm(b6)/ %s", 0},}},
			{{4, 8}, chord_arr_t{chord_t{ chord_t::BASS,"%saug", 0},chord_t{ chord_t::BASS,"%s+", 0},}},
			{{4, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj7/ %s", 2},}},
			{{4, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 2},}},
			{{4, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7#5", 0},}},
			{{4, 8, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7(#5)", 0},chord_t{ chord_t::BASS,"%sΔ7(#5)", 0},chord_t{ chord_t::ROOT_BASS,"%s(b6)/ %s", 0},}},
			{{4, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm/ %s", 1},chord_t{ chord_t::BASS,"%s6(omit5)", 0},}},
			{{4, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7add13", 0},}},
			{{4, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj13", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sm(add9)/ %s", 1},}},
			{{4, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7", 0},}},
			{{4, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMaj7", 0},chord_t{ chord_t::BASS,"%sΔ7", 0},}},
			{{5, 6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7add13/ %s", 2},}},
			{{5, 6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13b9/ %s", 2},}},
			{{5, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13(#9b9)/ %s", 2},}},
			{{5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%sMaj9(#11)/ %s", 1},}},
			{{5, 6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s13#9/ %s", 2},}},
			{{5, 6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(b9)/ %s", 0},}},
			{{5, 6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7b5/ %s", 1},}},
			{{5, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%ssus4", 0},chord_t{ chord_t::ROOT_BASS,"%s7sus4(no5)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%ssus2/ %s", 0},}},
			{{5, 7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 2},chord_t{ chord_t::ROOT_BASS,"%s7sus4(b9)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm(add9)/ %s", 0},}},
			{{5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4(b13)", 0},chord_t{ chord_t::BASS,"%s7b13sus", 0},chord_t{ chord_t::ROOT_BASS,"%sm(add9,11)/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%sMaj13/ %s", 2},}},
			{{5, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd9/ %s", 0},}},
			{{5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13sus4", 0},chord_t{ chord_t::ROOT_BASS,"%sm11/ %s", 1},}},
			{{5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s11/ %s", 1},}},
			{{5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4", 0},chord_t{ chord_t::ROOT_BASS,"%sm7(11)/ %s", 1},}},
			{{5, 7, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 1},}},
			{{5, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%s6/ %s", 1},}},
			{{5, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(#9)/ %s", 0},}},
			{{5, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7sus2/ %s", 2},}},
			{{5, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm(#11)/ %s", 0},}},
			{{5, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s/ %s", 0},}},
			{{5, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s13sus4", 0},chord_t{ chord_t::ROOT_BASS,"%sadd11/ %s", 0},}},
			{{5, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(#11)/ %s", 0},}},
			{{5, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7sus4(no5)", 0},chord_t{ chord_t::ROOT_BASS,"%ssus4/ %s", 0},chord_t{ chord_t::ROOT_BASS,"%ssus2/ %s", 1},}},
			{{5, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s5(#11)/ %s", 0},}},
			{{6, 7}, chord_arr_t{chord_t{ chord_t::BASS,"%s5(#11)", 0},}},
			{{6, 7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7(13)/ %s", 2},}},
			{{6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM11(no5)/ %s", 1},}},
			{{6, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj11/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%sm9(13)/ %s", 2},}},
			{{6, 7, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smM7(11)/ %s", 1},}},
			{{6, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7/ %s", 1},}},
			{{6, 8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7b9/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM7(13)/ %s", 2},}},
			{{6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7(b9#9)/ %s", 1},chord_t{ chord_t::ROOT_BASS,"%smM9(13)no5/ %s", 2},}},
			{{6, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s9/ %s", 1},}},
			{{6, 8, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s7#9/ %s", 1},}},
			{{6, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sdim/ %s", 0},}},
			{{6, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%s(b5)/ %s", 0},}},
			{{7, 8}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj7/ %s", 1},}},
			{{7, 8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sMaj9/ %s", 1},}},
			{{7, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm7/ %s", 1},}},
			{{7, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm9/ %s", 1},}},
			{{7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%s7(omit 3)", 0},}},
			{{7, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd11/ %s", 0},}},
			{{8, 9}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj7/ %s", 1},}},
			{{8, 9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%smMaj9/ %s", 1},}},
			{{8, 10}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sadd9/ %s", 0},}},
			{{9, 11}, chord_arr_t{chord_t{ chord_t::ROOT_BASS,"%sm(add9)/ %s", 0},}}
		};
	const chord_item_t scale_table[] = {
			{{1, 3, 4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sDiminished", 0},chord_t{ chord_t::NONE,"Half - Whole", 0},}},
			{{1, 3, 4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sAltered", 0},chord_t{ chord_t::NONE,"Super Locrian", 0},}},
			{{1, 3, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sLocrian", 0},}},
			{{1, 3, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sPhrygian", 0},}},
			{{1, 3, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sDorian(b2)", 0},}},
			{{1, 4, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sMixolydian(b9b13)", 0},chord_t{ chord_t::NONE,"Phrygian Dominant", 0},}},
			{{2, 3, 4, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sBebop Minor", 0},}},
			{{2, 3, 5, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sDiminished", 0},chord_t{ chord_t::NONE,"Whole - Half", 0},}},
			{{2, 3, 5, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sLocrian Natural(9)", 0},}},
			{{2, 3, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sAeolian", 0},chord_t{ chord_t::NONE,"Natural Minor", 0},}},
			{{2, 3, 5, 7, 8, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sHarmonic Minor", 0},}},
			{{2, 3, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sDorian", 0},}},
			{{2, 3, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sMelodic Minor", 0},}},
			{{2, 4, 5, 7, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sBebop Major", 0},}},
			{{2, 4, 5, 7, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sMixolydian(b13)", 0},chord_t{ chord_t::NONE,"Melodic Major(down)", 0},}},
			{{2, 4, 5, 7, 8, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sHarmonic Major", 0},}},
			{{2, 4, 5, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sMixolydian", 0},}},
			{{2, 4, 5, 7, 9, 10, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sBebop Dominant", 0},}},
			{{2, 4, 5, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sIonian", 0},chord_t{ chord_t::NONE,"Natural Major", 0},}},
			{{2, 4, 6, 7, 9, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sLydian Dominant", 0},}},
			{{2, 4, 6, 7, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sLydian", 0},}},
			{{2, 4, 6, 8, 9, 11}, chord_arr_t{chord_t{ chord_t::BASS,"%sLydian Augmented", 0},}},
			{{2, 4, 6, 8, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sWhole Tone", 0},}},
			{{2, 4, 7, 9}, chord_arr_t{chord_t{ chord_t::BASS,"%sPentatonic Major", 0},}},
			{{3, 4, 5, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sBlues(add3)", 0},}},
			{{3, 5, 6, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sBlues", 0},}},
			{{3, 5, 7, 10}, chord_arr_t{chord_t{ chord_t::BASS,"%sPentatonic Minor", 0},}}
		};
}
namespace chord {
	typedef array<uint8_t, 256> midi_key_states_t;
	const chord_item_t* find(key_t const& key, const chord_item_t* data, size_t size) {
		auto itm = chord_item_t{ key, chord_arr_t{} };
		auto it = lower_bound(data, data + size, key, [](chord_item_t const& lhs, key_t const& key) {return lhs.first < key; });
		if (it && it->first == key) return it;
		return nullptr;
	}
	template<typename T> const int format(midi_key_states_t const& state, span<T>&& lines) {
		static vector<uint8_t> keys(256), crange(256);		
		keys.clear(); for (int i = 0;i < 256;i++) if (state[i]) keys.push_back(i);
		if (!keys.size()) return 0;
		// push keys into the same octave & sorted
		// match keys after the root note
		crange.clear(); for (int i = 0;i < keys.size() - 1;i++) crange.push_back((keys[i + 1] - keys[0]) % 12);
		sort(crange.begin(), crange.end());		
		crange.resize(unique(crange.begin(), crange.end()) - crange.begin());
		static key_t chord_keys; fill(chord_keys.begin(), chord_keys.end(), 0);		
		copy(crange.begin() + (crange.size() > 1 && crange[0] == 0), crange.end(), chord_keys.begin());
		// find chord & scale (if applicable)
		uint8_t bass_k = keys[0] % 12;
		auto chord_v = find(chord_keys, chord_table, extent_of(chord_table));
		auto scale_v = find(chord_keys, scale_table, extent_of(scale_table));
		auto line_it = lines.begin();
		// chords
		if (chord_v) {
			for (auto& v : chord_v->second) {
				uint8_t nth_k = (keys[0] + chord_keys[v.nth_root]) % 12;
				v.format_to_string(*line_it, key_table[bass_k], key_table[nth_k]);
				line_it++;
			}
		}
		// intervals
		if (crange.size() && crange.size() < 3 && keys.size() > 1) {
			if (crange.size() == 1)
				sprintf(*line_it, "%s %s", key_table[bass_k],interval_table[crange[0]]), line_it++;
			else
				sprintf(*line_it, "%s %s", key_table[bass_k],interval_table[crange[1]]), line_it++;
		}
		// scales
		if (scale_v && keys.size() > 1) {
			for (auto& v : scale_v->second) {
				uint8_t nth_k = (keys[0] + chord_keys[v.nth_root]) % 12;
				v.format_to_string(*line_it, key_table[bass_k], key_table[nth_k]);
				line_it++;
			}
		}
		// single notes
		if (keys.size() == 1) {
			sprintf(*line_it, "%s", key_table[bass_k]);
			line_it++;
		}
		return line_it - lines.begin();
	}
}
